### Word  Embedding: 
Word Embedding is representation words in a numerical format. Usually 100 to 500 numneric values considered to represent a word in word Embedding
#### Example:
##### sea : Vector1= [ 0.29919001 -0.11731    -0.0089925  -0.37059    -0.06722     0.15163  -0.061105    0.29587001  0.36515999 -1.50870001] ## 10 numeric values                                      
#### ocean: Vector2 = [[ 0.12654001 -0.64278001 -0.45298001 -0.01482    -0.14442     0.16745999 -0.085392   -0.20653     0.58867002 -1.45519996]] ## 10 numeric values             
#### car: Vector3= [[ 0.46443     0.37729999 -0.21459    -0.50768    -0.24575999  0.08134 0.10145     0.25154999 -0.36151999 -1.60300004]] ## 10 numeric values 
The similarity between Vecor1 & Vector2 are high compare to Vector1 and Vecror3    
These word's vector can be used in multiple NLP taskes like finding similarity between two words and also can be useud in classification task

### word2vec:
It creates word to numeric vector by learning large text corpus using Deep Learning

#### Use of Word Embedding in Keras to build LSTM Model

#### Tokenizer
Its Keras class in text preprocessing especially used for text tokenization and getting token level information using multiple methods
#### Methods
- fit_on_texts : It creates index to all tokens which can be seen using word_index property
- texts_to_sequences : It maps the index to popular words to the given text from fit_on_texts

### Use  Pre Trainied Word Embeddings in Modelling 
   - Loading the GloVe Word Embedding
   - Create Embedding Matrix : It maps numeric vector each words received from tokenization
   - Create Embedding Layer using values of Embedding Matrix ## It makes the matrix compatible
   
### Create X ( Text to be Classified) and y (Classification)
- Convert text into sequence using text_sequence
- pad the text sequence to get X
- convert values y to array

### Fit The model



In [6]:
from keras.preprocessing.text import Tokenizer

sample_text = ["@user when a father is dysfunctional and is so selfish he drags his kids into his dysfunction. #run",
              "it's unbelievable that in the 21st century we'd need something like this. again. #neverump #xenophobia",
              "@user @user thanks for #lyft credit i can't use cause they don't offer wheelchair vans in pdx. #disapointed #getthanked"]
num_words = 100
tokenizer = Tokenizer(nb_words=num_words) ## Tokenize the texts

tokenizer.fit_on_texts(sample_text) ## Assiging inxed to all token

print tokenizer.word_index ## See the index of all tokens 
#print "#### #######"

{'and': 5, 'lyft': 6, "don't": 20, 'when': 21, 'is': 2, 'unbelievable': 27, "we'd": 11, 'in': 3, 'need': 12, 'dysfunction': 13, 'selfish': 14, '21st': 15, 'for': 17, 'credit': 43, 'neverump': 18, "it's": 19, 'century': 7, 'father': 8, 'getthanked': 22, 'that': 29, 'dysfunctional': 23, 'disapointed': 32, 'cause': 25, 'into': 26, 'vans': 9, 'his': 4, 'run': 28, 'offer': 10, 'something': 47, 'use': 30, 'user': 1, 'they': 31, 'he': 33, 'a': 34, 'again': 35, 'kids': 36, 'like': 37, 'pdx': 39, 'i': 16, 'wheelchair': 41, 'xenophobia': 42, 'so': 44, 'this': 40, 'drags': 24, 'the': 45, "can't": 46, 'thanks': 38}


In [ ]:
#import enchant

In [7]:
print tokenizer.texts_to_sequences(["we'd need something like this. again. #neverump #xenophobia"])

[[11, 12, 47, 37, 40, 35, 18, 42]]


In [8]:
#### Load the Pre Trained Glove Word Embedding 

from tqdm import tqdm
import numpy as np

embeddings_index = {}
f = open('glove.6B.300d.txt')
for line in tqdm(f):
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    embeddings_index[word] = coefs
f.close()

print('Found %s word vectors.' % len(embeddings_index))

400000it [00:23, 17003.24it/s]

Found 400000 word vectors.


In [41]:
#embeddings_index
import numpy as np
#print embeddings_index['car']## Find the word vector
print np.corrcoef(embeddings_index['car'],embeddings_index['bus'])

[[ 1.          0.56586078]
 [ 0.56586078  1.        ]]


In [42]:
## Create the word Embedding Matrix
word_index = tokenizer.word_index  ### Number of words in the text sample
print len(word_index)
embedding_matrix = np.zeros((len(word_index) + 1, 300)) ### use same dimension length of embedding vector
for word, i in tqdm(word_index.items()):
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
        embedding_matrix[i] = embedding_vector

print embedding_matrix.shape

100%|██████████| 47/47 [00:00<00:00, 214507.39it/s]

47
(48, 300)


In [43]:
temp = pd.DataFrame(embedding_matrix.tolist())
temp

0         1         2         3         4         5         6    \
0   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
1  -1.116900  0.280150  0.129010 -0.857920  0.188440  0.007536 -0.295840   
2  -0.174900  0.229560  0.249240 -0.205120 -0.122940  0.021297 -0.238150   
3  -0.443990  0.128170 -0.252470 -0.185820 -0.166140  0.259090 -0.226780   
4  -0.221300  0.471390 -0.166580 -0.261280  0.040058 -0.105270 -0.195980   
5   0.038466 -0.039792  0.082747 -0.389230 -0.214310  0.170200 -0.025657   
6  -0.240340 -0.625840 -0.466920  0.060747 -0.690370 -0.075706 -0.195160   
7   0.274460 -0.763480 -0.260650 -0.487760  0.630300  0.293580 -0.421800   
8  -0.138740 -0.083454  0.301410 -0.121890 -0.111670 -0.081257 -0.212770   
9   0.086105 -0.277490 -0.140280 -0.229720  0.069679  0.083296  0.443400   
10 -0.193960 -0.202200  0.120970  0.364070  0.167460  0.133910  0.498660   
11  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
12 -0.389300 -0.037647 -0.362420 -0.088854  0.135430  0.337070  0.167100   
13  0.085652  0.284420  0.513990  0.294500 -0.150920  0.243260  0.130250   
14  0.060503 -0.335540  0.381460  0.190510  0.944020  0.611290  0.003764   
15 -0.198060 -0.230970 -0.420220 -0.257870 -0.143260  0.459360 -0.685820   
16 -0.132920  0.169850 -0.143600 -0.088722  0.079510 -0.142120 -0.024209   
17 -0.241320  0.120630  0.191900 -0.266920  0.061076 -0.022878  0.580170   
18  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
19  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
20  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
21 -0.141540  0.027303  0.135940 -0.120160  0.316880 -0.002833  0.049514   
22  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
23  0.136610  0.002181  0.120180  0.263550  0.268590  0.258980 -0.377540   
24  0.154590 -0.028190  0.174740  0.265690  0.292010  0.324880 -0.402280   
25  0.013162  0.141820  0.001062 -0.228430 -0.164140 -0.305440  0.594340   
26 -0.182340 -0.192090  0.151670 -0.048763  0.283540 -0.025568 -0.398820   
27  0.305830  0.190110  0.061880  0.599350  0.152570 -0.120680  0.047957   
28  0.352160  0.383330  0.046800  0.500030  0.228310  0.357800  0.044829   
29 -0.182560  0.498510 -0.163900 -0.174430 -0.163820 -0.044109  0.279570   
30 -0.105150  0.134070  0.138390 -0.647000  0.124300  0.027522 -0.206510   
31 -0.266250  0.479640 -0.388180  0.039296 -0.020338  0.168600  0.315850   
32  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
33 -0.520570  0.495620  0.032912 -0.060807 -0.099912 -0.299140  0.303760   
34 -0.297120  0.094049 -0.096662 -0.344000 -0.184830 -0.123290 -0.116560   
35  0.004946  0.041202 -0.014766 -0.059360  0.144710 -0.018713  0.202750   
36 -0.164750  0.023265  0.086147  0.375980 -0.059698  0.895480 -0.137380   
37 -0.134430 -0.016333  0.091076 -0.135120  0.278520  0.291780 -0.211260   
38  0.184670 -0.167180  0.001457  0.010190  0.203580  0.231270 -0.250230   
39  0.251900 -0.473650  0.138730  0.301180  0.159190 -0.066448 -0.750990   
40 -0.204370  0.164310  0.041794 -0.137080 -0.297790  0.334400 -0.069955   
41 -0.106940 -0.659200  0.057421 -0.884830  0.166830  0.368160 -0.459860   
42  0.583530  0.332860  0.431760 -0.253440 -0.686020 -0.202130 -0.199980   
43  0.447540  0.036813 -0.352930  0.128830  0.063930 -0.251270  0.572220   
44 -0.245610  0.068010  0.182540 -0.295510  0.018007  0.168110  0.191090   
45  0.046560  0.213180 -0.007436 -0.458540 -0.035639  0.236430 -0.288360   
46  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
47 -0.199270  0.042162 -0.182290 -0.048795  0.048476 -0.330350  0.047423   

         7         8         9      ...          290       291       292  \
0   0.000000  0.000000  0.000000    ...     0.000000  0.000000  0.000000   
1  -0.149820  0.249070 -1.567700    ...    -0.014962 -0.361060 -0.552190   
2   0.137370 -0.089130 -2.060700    ...     0.313570 -0.

In [44]:
## Create Embedding Layer
from keras.layers import Embedding
#embedding_layer = Embedding(len(word_index) + 1, 300, input_length=40, dropout=0.2)
embedding_layer = Embedding(embedding_matrix.shape[0],
                            embedding_matrix.shape[1],
                            weights=[embedding_matrix],
                            input_length=5)  ## Input Length is maximum words to be considered

In [46]:
## from keras.preprocessing.sequence import pad_sequences
from keras.preprocessing.sequence import pad_sequences
X = tokenizer.texts_to_sequences(sample_text)
X = pad_sequences(X, maxlen=5)
print(X)
#y = [0,1,0]

[[36 26  4 13 28]
 [37 40 35 18 42]
 [ 9  3 39 32 22]]


array([[36, 26,  4, 13, 28],
       [37, 40, 35, 18, 42],
       [ 9,  3, 39, 32, 22]], dtype=int32)

In [47]:
#from keras.layers import Bidirectional
from keras.models import Sequential
from keras.layers import Dense, Input, Flatten
from keras.layers.recurrent import LSTM, GRU

model = Sequential()
model.add(embedding_layer)
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.layers[0].trainable=False
model.compile(loss='binary_crossentropy', optimizer='rmsprop')
model.fit(X, y=y, batch_size=20, nb_epoch=700, verbose=0, validation_split=0.2)

In [30]:
import pandas as pd
data_train = pd.read_csv('train_E6oV3lV.csv')
data_train.head()

id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

In [ ]:
#### Bulid the Final Model for Text classification

In [31]:
import numpy as np
import pandas as pd
import cPickle
from collections import defaultdict
import re

from bs4 import BeautifulSoup

import sys
import os

os.environ['KERAS_BACKEND']='theano'

from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.utils.np_utils import to_categorical

from keras.layers import Embedding
from keras.layers import Dense, Input, Flatten
from keras.layers import Conv1D, MaxPooling1D, Embedding, Merge, Dropout,GlobalAveragePooling1D
from keras.models import Model

In [32]:
from nltk.corpus import stopwords
stops = set(stopwords.words("english"))

## Add spell checker and short form to long form 
remove_words = ['user',"frm", "u", "urs", "n", "ur", "b", "mro", "mo", "tmr", "k", "ok",
"lol", "haha", "w", "moro", "yah", "cya", "cu", "eh", "hm", "hmm",
"yall", "xoxo", "yolo", "em", "v", "ver", "hav", "vry", "shud", "wer",
"abt", "bc", "wen", "jus", "tht", "fr", "hs", "r", "wud", "cud"]

def PreProcess(tweet):
    #tweet = str(tweet)
    tweet = tweet.lower()
    tweet = BeautifulSoup(tweet, "lxml").get_text()
    tweet = re.sub("[^a-zA-Z]", " ", tweet)
    tweet = ' '.join([word for word in tweet.split() if word not in stops]) ## Remove eng stop words
    tweet = ' '.join([word for word in tweet.split() if word not in remove_words]) ## Remove specific words
    return tweet

In [33]:
import pandas as pd
import numpy as np
from tqdm import tqdm
from keras.models import Sequential
from keras.layers.core import Dense, Activation, Dropout
from keras.layers.embeddings import Embedding
from keras.layers.recurrent import LSTM, GRU
from keras.layers.normalization import BatchNormalization
from keras.utils import np_utils
#from keras.engine.topology import Merge
from keras.layers import TimeDistributed, Lambda
from keras.layers import Convolution1D, GlobalMaxPooling1D
from keras.callbacks import ModelCheckpoint
from keras import backend as K
from keras.layers.advanced_activations import PReLU
from keras.preprocessing import sequence, text
from keras.layers import Bidirectional
from keras.layers.normalization import BatchNormalization

data = pd.read_csv('train_E6oV3lV.csv')
#data.tweet = data.tweet.apply(PreProcess)

y = data.label.values

tk = text.Tokenizer(nb_words=200000)

max_len = 40


tk.fit_on_texts(data.tweet.values.astype(str))
x = tk.texts_to_sequences(data.tweet.values)
x = sequence.pad_sequences(x, maxlen=max_len)


word_index = tk.word_index
#ytrain_enc = np_utils.to_categorical(y)
embeddings_index = {}
f = open('glove.6B.300d.txt')
for line in tqdm(f):
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    embeddings_index[word] = coefs
f.close()

print('Found %s word vectors.' % len(embeddings_index))

embedding_matrix = np.zeros((len(word_index) + 1, 300))
for word, i in tqdm(word_index.items()):
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
        embedding_matrix[i] = embedding_vector

max_features = 200000

embedding_layer = Embedding(len(word_index) + 1, 300, input_length=40, dropout=0.2)


400000it [00:22, 17503.65it/s]
100%|██████████| 45889/45889 [00:00<00:00, 289511.44it/s]

Found 400000 word vectors.



/Users/jeebanswain/anaconda2/lib/python2.7/site-packages/keras/legacy/interfaces.py:123: UserWarning: The `dropout` argument is no longer support in `Embedding`. You can apply a `keras.layers.SpatialDropout1D` layer right after the `Embedding` layer to get the same behavior.
  warnings.warn('The `dropout` argument is no longer support in `Embedding`. '


In [34]:
model1 = Sequential()
model1.add(embedding_layer)
model1.add(((LSTM(100, dropout_W=0.2, dropout_U=0.2))))
model1.add(BatchNormalization())

model1.add(Dense(100))
model1.add(PReLU())
model1.add(Dropout(0.2))
model1.add(BatchNormalization())

model1.add(Dense(1))
model1.add(Activation('sigmoid'))


model1.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
checkpoint = ModelCheckpoint('weights.h5', monitor='val_acc', save_best_only=True, verbose=2)


/Users/jeebanswain/anaconda2/lib/python2.7/site-packages/keras/legacy/interfaces.py:86: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(100, dropout=0.2, recurrent_dropout=0.2)`
  '` call to the Keras 2 API: ' + signature)


In [3]:
model1.fit([x], y=y, batch_size=384, nb_epoch=10,
                 verbose=1, validation_split=0.1, shuffle=True, callbacks=[checkpoint])